### ISSUE TITLE
CSV output

### ISSUE THREAD

**Issue by debuglevel** [Helyux/BBB-Readable-Feedback#1]
First of all: Thank you so much, this tool probably cures the headache of everybody who wanted to use the feedback function ;-)

It would be nice if there is some "standarized" output; e.g. a CSV file. One could then just open it in Excel/LibreOffice/R and do some statistics magic.

**Comment by Helyux** [comment]
Yes sure, good idea.
I'll look into it when I've got some time on my hand.

**Comment by Helyux** [comment]
Hey @debuglevel i added a `-csv` switch in the latest commit. (757d4be)
