### ISSUE TITLE
How to show the feedback log as URL link in the GreenLight Organization Page

### ISSUE THREAD

**Issue by HasanMajhali** [Helyux/BBB-Readable-Feedback#2]
First of all: Thank you so much
Please How to show the feedback log as URL link in the GreenLight Organization Page when clicked it shows the log within page
like this example 

![feedback](https://user-images.githubusercontent.com/52064854/107743097-5574d300-6d21-11eb-8874-1dafc69cba79.jpg)

**Comment by Helyux** [comment]
Hi Hasan,
i'm sorry to tell you that i can't make that work.
What your asking seems to be a feature that would need to be implemented by the greenlight devs.

**Comment by lonesomewalker** [comment]
Depends ;-)

If you know what a bind-mount is, you could simply mount the BBB filesystem into the docker container, et voila... ;-)

**Comment by HasanMajhali** [comment]
> Depends ;-)
> 
> If you know what a bind-mount is, you could simply mount the BBB filesystem into the docker container, et voila... ;-)

thanks for your reply 
No I don't Know what a bind-mount ,
if there any Links to read about it and learn how to make it work .
